name: Tournaments

on:
  workflow_dispatch:
  schedule:
    - cron: "13 * * * *" # every hour at 13 minutes past the hour
    - cron: "33 * * * *" # every hour at 33 minutes past the hour
    - cron: "53 * * * *" # every hour at 53 minutes past the hour

jobs:
  query:
    concurrency:
      group: scheduled-forecast-query
      cancel-in-progress: false
    outputs:
      post_ids: ${{ steps.post_ids.outputs.post_ids }}
    runs-on: ubuntu-latest
    steps:
      - id: post_ids
        run: |
          echo "post_ids=$(curl "https://www.metaculus.com/api/posts/?forecast_type=binary,discrete,multiple_choice,numeric&include_description=true&not_forecaster_id=$METACULUS_BOT_ID&offset=0&statuses=open&tournaments=minibench&tournaments=summer-futureeval-2026&tournaments=fall-futureeval-2026" -H "Authorization: Token $METACULUS_BOT_API_TOKEN" \
            | jq -c '.results | map(.id)')" >> $GITHUB_OUTPUT
        env:
          METACULUS_BOT_API_TOKEN: ${{ secrets.METACULUS_BOT_API_TOKEN }}
          METACULUS_BOT_ID: ${{ secrets.METACULUS_BOT_ID }}

  enqueue:
    if: ${{ needs.query.outputs.post_ids != '' && needs.query.outputs.post_ids != '[]' }}
    needs: query
    strategy:
      fail-fast: false
      matrix:
        post_id: ${{ fromJSON(needs.query.outputs.post_ids) }}
    concurrency:
      group: ${{ github.workflow }}+enqueue+${{ matrix.post_id }}
      cancel-in-progress: false
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      ASKNEWS_API_KEY: ${{ secrets.ASKNEWS_API_KEY }}
      DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
      METACULUS_BOT_API_TOKEN: ${{ secrets.METACULUS_BOT_API_TOKEN }}
      METACULUS_BOT_ID: ${{ secrets.METACULUS_BOT_ID }}
      OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}
      OPEN_ROUTER_OPENAI_API_KEY: ${{ secrets.OPEN_ROUTER_OPENAI_API_KEY }}
      PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
    uses: ./.github/workflows/forecast.yml
    with:
      post_id: ${{ matrix.post_id }}
